---
apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
 components:
   dashboard:
      managementState: Managed
   aipipelines:
      managementState: Managed
   feastoperator:
      managementState: Managed
   kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headed
      modelsAsService:
        managementState: Managed
   llamastackoperator:
      managementState: Managed
   kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Unmanaged
   modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
   ray:
      managementState: Managed
   workbenches:
      managementState: Managed
   trainingoperator:
      managementState: Managed
   trustyai:
      managementState: Managed
